export class RDWCar {


  kenteken : string;
  voertuigsoort: string;
  merk: string;
  handelsbenaming: string;
  vervaldatum_apk : number;
  datum_tenaamstelling : number;
  bruto_bpm : number;
  inrichting: string;
  aantal_zitplaatsen;
  eerste_kleur: string;
  tweede_kleur: string;
  aantal_cilinders : number;
  cilinderinhoud : number;
  massa_ledig_voertuig : number;
  toegestane_maximum_massa_voertuig : number;
  massa_rijklaar : number;
  zuinigheidslabel: string;
  datum_eerste_toelating : number;
  datum_eerste_afgifte_nederland : number;
  wacht_op_keuren: string;
  catalogusprijs;
  wam_verzekerd: string;
  aantal_deuren : number;
  aantal_wielen : number;
  afstand_hart_koppeling_tot_achterzijde_voertuig : number;
  afstand_voorzijde_voertuig_tot_hart_koppeling : number;
  lengte : number;
  breedte : number;
  europese_voertuigcategorie: string;
  plaats_chassisnummer: string;
  technische_max_massa_voertuig : number;
  typegoedkeuringsnummer : string;
  variant : string;
  uitvoering : string;
  volgnummer_wijziging_eu_typegoedkeuring : number;
  vermogen_massarijklaar : number;
  wielbasis : number;
  export_indicator : string;
  openstaande_terugroepactie_indicator : string;
  taxi_indicator : string;
  maximum_massa_samenstelling : number;
  aantal_rolstoelplaatsen : number;
  api_gekentekende_voertuigen_assen : string;
  api_gekentekende_voertuigen_brandstof : string;
  api_gekentekende_voertuigen_carrosserie : string;
  api_gekentekende_voertuigen_carrosserie_specifiek : string;
  api_gekentekende_voertuigen_voertuigklasse : string;


  constructor(kenteken: string, voertuigsoort: string, merk: string, handelsbenaming: string, vervaldatum_apk: number, datum_tenaamstelling: number, bruto_bpm: number, inrichting: string, aantal_zitplaatsen, eerste_kleur: string, tweede_kleur: string, aantal_cilinders: number, cilinderinhoud: number, massa_ledig_voertuig: number, toegestane_maximum_massa_voertuig: number, massa_rijklaar: number, zuinigheidslabel: string, datum_eerste_toelating: number, datum_eerste_afgifte_nederland: number, wacht_op_keuren: string, catalogusprijs, wam_verzekerd: string, aantal_deuren: number, aantal_wielen: number, afstand_hart_koppeling_tot_achterzijde_voertuig: number, afstand_voorzijde_voertuig_tot_hart_koppeling: number, lengte: number, breedte: number, europese_voertuigcategorie: string, plaats_chassisnummer: string, technische_max_massa_voertuig: number, typegoedkeuringsnummer: string, variant: string, uitvoering: string, volgnummer_wijziging_eu_typegoedkeuring: number, vermogen_massarijklaar: number, wielbasis: number, export_indicator: string, openstaande_terugroepactie_indicator: string, taxi_indicator: string, maximum_massa_samenstelling: number, aantal_rolstoelplaatsen: number, api_gekentekende_voertuigen_assen: string, api_gekentekende_voertuigen_brandstof: string, api_gekentekende_voertuigen_carrosserie: string, api_gekentekende_voertuigen_carrosserie_specifiek: string, api_gekentekende_voertuigen_voertuigklasse: string) {
    this.kenteken = kenteken;
    this.voertuigsoort = voertuigsoort;
    this.merk = merk;
    this.handelsbenaming = handelsbenaming;
    this.vervaldatum_apk = vervaldatum_apk;
    this.datum_tenaamstelling = datum_tenaamstelling;
    this.bruto_bpm = bruto_bpm;
    this.inrichting = inrichting;
    this.aantal_zitplaatsen = aantal_zitplaatsen;
    this.eerste_kleur = eerste_kleur;
    this.tweede_kleur = tweede_kleur;
    this.aantal_cilinders = aantal_cilinders;
    this.cilinderinhoud = cilinderinhoud;
    this.massa_ledig_voertuig = massa_ledig_voertuig;
    this.toegestane_maximum_massa_voertuig = toegestane_maximum_massa_voertuig;
    this.massa_rijklaar = massa_rijklaar;
    this.zuinigheidslabel = zuinigheidslabel;
    this.datum_eerste_toelating = datum_eerste_toelating;
    this.datum_eerste_afgifte_nederland = datum_eerste_afgifte_nederland;
    this.wacht_op_keuren = wacht_op_keuren;
    this.catalogusprijs = catalogusprijs;
    this.wam_verzekerd = wam_verzekerd;
    this.aantal_deuren = aantal_deuren;
    this.aantal_wielen = aantal_wielen;
    this.afstand_hart_koppeling_tot_achterzijde_voertuig = afstand_hart_koppeling_tot_achterzijde_voertuig;
    this.afstand_voorzijde_voertuig_tot_hart_koppeling = afstand_voorzijde_voertuig_tot_hart_koppeling;
    this.lengte = lengte;
    this.breedte = breedte;
    this.europese_voertuigcategorie = europese_voertuigcategorie;
    this.plaats_chassisnummer = plaats_chassisnummer;
    this.technische_max_massa_voertuig = technische_max_massa_voertuig;
    this.typegoedkeuringsnummer = typegoedkeuringsnummer;
    this.variant = variant;
    this.uitvoering = uitvoering;
    this.volgnummer_wijziging_eu_typegoedkeuring = volgnummer_wijziging_eu_typegoedkeuring;
    this.vermogen_massarijklaar = vermogen_massarijklaar;
    this.wielbasis = wielbasis;
    this.export_indicator = export_indicator;
    this.openstaande_terugroepactie_indicator = openstaande_terugroepactie_indicator;
    this.taxi_indicator = taxi_indicator;
    this.maximum_massa_samenstelling = maximum_massa_samenstelling;
    this.aantal_rolstoelplaatsen = aantal_rolstoelplaatsen;
    this.api_gekentekende_voertuigen_assen = api_gekentekende_voertuigen_assen;
    this.api_gekentekende_voertuigen_brandstof = api_gekentekende_voertuigen_brandstof;
    this.api_gekentekende_voertuigen_carrosserie = api_gekentekende_voertuigen_carrosserie;
    this.api_gekentekende_voertuigen_carrosserie_specifiek = api_gekentekende_voertuigen_carrosserie_specifiek;
    this.api_gekentekende_voertuigen_voertuigklasse = api_gekentekende_voertuigen_voertuigklasse;
  }
}
